name: Issue Status Tracker

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  export-issue-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install PyGithub

    - name: Export Issue Status to CSV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        mkdir -p Prozessmetriken
        python export_issues.py

    - name: Commit CSV File
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add Prozessmetriken/issue_status_metrics.csv
        git commit -m "Update issue status metrics"
        git push
